name: "build"
on:
  push:
    branches:
    - "!dependabot/*"
    - "*"
  pull_request:
    branches:
    - "*"
jobs:
  lint: 
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-go@v2"
      with:
        go-version: ^1.16
    - name: "go fmt"
      run: |
        GOFMT_OUTPUT="$(gofmt -l `find ./ -name '*.go' | grep -v vendor` 2>&1)"

        if [ -n "$GOFMT_OUTPUT" ]; then
          echo "All the following files are not correctly formatted"
          echo "${GOFMT_OUTPUT}"
          exit 1
        fi
    - name: "go imports"
      run: |
        exec 5>&1
        GOIMPORTS_OUTPUT="$(goimports -l -w `find ./ -name '*.go' | grep -v vendor` | tee /dev/fd/5)"

        if [ -n "$GOIMPORTS_OUTPUT" ]; then
          echo "All following has imports not properly ordered"
          echo "${GOIMPORTS_OUTPUT}"

          exit 1
        fi
    - name: "go mod tidy"
      run: |
        GO_MOD_OUPUT="$(go mod tidy -v 2>&1)"

        if [[ $GO_MOD_OUPUT == *"unused"* ]]; then
          echo "${GO_MOD_OUPUT}"
          exit 1
        fi
    - uses: golangci/golangci-lint-action@v2

  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-go@v2"
      with:
        go-version: ^1.16
    - name: "go build"
      run: "go build"
    - name: "go test"
      run: "go test ./..."
  docker:
    name: Build Docker image
    runs-on: ubuntu-20.04
    needs:
    - lint
    - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=ref::$(git status | head -1 | awk '{print $NF}' | sed 's#/#_#g')"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: |
            quay.io/jzelinskie/grpcwebproxy:${{ steps.vars.outputs.ref }}
      - name: Login to Quay
        uses: docker/login-action@v1
        if: github.event_name == 'push'
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ACCOUNT }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Push to Quay
        uses: docker/build-push-action@v2
        if: github.event_name == 'push'
        with:
          push: true
          tags: |
            quay.io/jzelinskie/grpcwebproxy:${{ steps.vars.outputs.ref }}
